import firebase_admin
from firebase_admin import credentials, firestore
from datetime import datetime, timezone

cred = credentials.Certificate('/home/ayiecho/projects/yan_website/serviceAccount.json')
if not firebase_admin._apps:
    firebase_admin.initialize_app(cred)
db = firestore.client()

SCHOLARSHIPS = [
    {'title':'Wellcome Trust Scholarships Africa','provider':'Wellcome Trust','funding':'Full Scholarship','deadline':'Rolling','eligibility':'African researchers in health sciences','link':'https://wellcome.org','countries':'All African countries','level':'PhD & Postdoc','category':'scholarship'},
    {'title':'OFID Scholarship Award','provider':'OPEC Fund for International Development','funding':'Full Scholarship','deadline':'June annually','eligibility':'Citizens of OFID member countries','link':'https://ofid.org/scholarship','countries':'African OFID members','level':'Masters','category':'scholarship'},
    {'title':'African Union Scholarships','provider':'African Union Commission','funding':'Full Scholarship + Stipend','deadline':'March annually','eligibility':'African nationals under 35','link':'https://au.int/scholarships','countries':'All African countries','level':'Masters & PhD','category':'scholarship'},
    {'title':'Japan MEXT Scholarship','provider':'Japanese Government','funding':'Full Scholarship','deadline':'May annually','eligibility':'African students for study in Japan','link':'https://www.studyinjapan.go.jp','countries':'All African countries','level':'Undergraduate & Graduate','category':'scholarship'},
    {'title':'Korean Government Scholarship KGSP','provider':'Korean Government','funding':'Full Scholarship','deadline':'March annually','eligibility':'African students for study in Korea','link':'https://www.niied.go.kr','countries':'All African countries','level':'Undergraduate & Graduate','category':'scholarship'},
    {'title':'Chinese Government Scholarship','provider':'Chinese Government','funding':'Full Scholarship','deadline':'April annually','eligibility':'African students for study in China','link':'https://www.csc.edu.cn','countries':'All African countries','level':'Undergraduate & Graduate','category':'scholarship'},
    {'title':'Rotary Foundation Scholarships','provider':'Rotary International','funding':'Up to $30,000 USD','deadline':'May annually','eligibility':'African graduates with leadership potential','link':'https://www.rotary.org/scholarships','countries':'All African countries','level':'Masters','category':'scholarship'},
    {'title':'AAUW International Fellowships','provider':'American Association of University Women','funding':'$18,000-$30,000 USD','deadline':'November annually','eligibility':'African women graduates','link':'https://www.aauw.org/fellowships','countries':'All African countries','level':'Masters & PhD','category':'scholarship'},
    {'title':'Mastercard Foundation at University of Toronto','provider':'Mastercard Foundation','funding':'Full Scholarship','deadline':'November annually','eligibility':'African students with financial need','link':'https://mastercardfoundationscholars.utoronto.ca','countries':'All African countries','level':'Undergraduate','category':'scholarship'},
    {'title':'Edinburgh Global Research Scholarships','provider':'University of Edinburgh','funding':'Full PhD Scholarship','deadline':'January annually','eligibility':'Outstanding African PhD applicants','link':'https://www.ed.ac.uk/student-funding/scholarships','countries':'All African countries','level':'PhD in UK','category':'scholarship'},
    {'title':'Rhodes Scholarship Africa','provider':'Rhodes Trust','funding':'Full Scholarship Oxford','deadline':'July annually','eligibility':'Outstanding African graduates under 25','link':'https://www.rhodeshouse.ox.ac.uk','countries':'Selected African countries','level':'Masters & PhD at Oxford','category':'scholarship'},
    {'title':'Clarendon Fund Scholarships Oxford','provider':'University of Oxford','funding':'Full Scholarship','deadline':'January annually','eligibility':'Outstanding African graduates','link':'https://www.ox.ac.uk/clarendon','countries':'All African countries','level':'Masters & PhD at Oxford','category':'scholarship'},
    {'title':'Cambridge Trust Scholarships','provider':'University of Cambridge','funding':'Full Scholarship','deadline':'December annually','eligibility':'Outstanding African students','link':'https://www.cambridge.org/cambridgetrust','countries':'All African countries','level':'Masters & PhD at Cambridge','category':'scholarship'},
    {'title':'Hubert Humphrey Fellowship Program','provider':'US Department of State','funding':'Full Fellowship','deadline':'October annually','eligibility':'Mid-career African professionals','link':'https://www.humphreyfellowship.org','countries':'All African countries','level':'Professional Development USA','category':'scholarship'},
    {'title':'Australia Awards Scholarships Africa','provider':'Australian Government','funding':'Full Scholarship','deadline':'April annually','eligibility':'African students for study in Australia','link':'https://www.australiaawards.gov.au','countries':'Selected African countries','level':'Masters & PhD in Australia','category':'scholarship'},
    {'title':'Swedish Institute Scholarships','provider':'Swedish Institute','funding':'Full Scholarship','deadline':'February annually','eligibility':'African students for study in Sweden','link':'https://si.se/scholarships','countries':'Selected African countries','level':'Masters in Sweden','category':'scholarship'},
    {'title':'VLIR-UOS Scholarships Belgium','provider':'Belgian Government','funding':'Full Scholarship','deadline':'February annually','eligibility':'African students for study in Belgium','link':'https://www.vliruos.be/scholarships','countries':'Selected African countries','level':'Masters in Belgium','category':'scholarship'},
    {'title':'Nuffic Orange Knowledge Programme','provider':'Dutch Government','funding':'Full Scholarship','deadline':'Rolling','eligibility':'African professionals for study in Netherlands','link':'https://www.nuffic.nl/okp','countries':'Selected African countries','level':'Short courses & Masters','category':'scholarship'},
    {'title':'IDRC Research Awards Africa','provider':'International Development Research Centre','funding':'Full Research Award','deadline':'Rolling','eligibility':'African researchers in development','link':'https://idrc.ca/awards','countries':'All African countries','level':'PhD & Postdoc','category':'scholarship'},
    {'title':'Intra-Africa Academic Mobility Scheme','provider':'European Commission','funding':'Full Scholarship','deadline':'Rolling','eligibility':'African students for study within Africa','link':'https://intra-africa.eu','countries':'All African countries','level':'Masters & PhD','category':'scholarship'},

    {'title':'Mastercard Foundation Scholars Program 2025','provider':'Mastercard Foundation','funding':'Full Scholarship','deadline':'Rolling','eligibility':'African students with demonstrated leadership','link':'https://mastercardfdn.org/scholars','countries':'All African countries','level':'Undergraduate & Graduate','category':'scholarship'},
    {'title':'African Development Bank Scholarship','provider':'African Development Bank','funding':'Full Scholarship + Stipend','deadline':'March 31 annually','eligibility':'African nationals pursuing Masters degree','link':'https://www.afdb.org','countries':'All African countries','level':'Masters','category':'scholarship'},
    {'title':'Chevening Scholarships 2025-2026','provider':'UK Government','funding':'Full Scholarship','deadline':'November annually','eligibility':'African professionals with 2 years work experience','link':'https://www.chevening.org','countries':'All African countries','level':'Masters in UK','category':'scholarship'},
    {'title':'Commonwealth Scholarship 2025','provider':'Commonwealth Scholarship Commission','funding':'Full Scholarship','deadline':'October annually','eligibility':'Commonwealth country citizens','link':'https://cscuk.fcdo.gov.uk','countries':'Commonwealth African nations','level':'Masters & PhD','category':'scholarship'},
    {'title':'Erasmus Mundus Joint Masters','provider':'European Commission','funding':'Full Scholarship + 1400/month','deadline':'January annually','eligibility':'African students with excellent academic record','link':'https://erasmus-plus.ec.europa.eu','countries':'All African countries','level':'Masters in Europe','category':'scholarship'},
    {'title':'DAAD Scholarship Germany 2025','provider':'DAAD Germany','funding':'Full Scholarship + 850/month','deadline':'October annually','eligibility':'African graduates with excellent grades','link':'https://www.daad.de/en','countries':'All African countries','level':'Masters & PhD in Germany','category':'scholarship'},
    {'title':'Mo Ibrahim Foundation Scholarship','provider':'Mo Ibrahim Foundation','funding':'Full Scholarship','deadline':'February annually','eligibility':'African nationals under 35','link':'https://mo.ibrahim.foundation','countries':'All African countries','level':'Masters at LSE','category':'scholarship'},
    {'title':'Aga Khan Foundation International Scholarship','provider':'Aga Khan Foundation','funding':'Partial to Full Scholarship','deadline':'March annually','eligibility':'Exceptional graduates from developing countries','link':'https://www.akdn.org/agency/akf','countries':'Selected African countries','level':'Masters','category':'scholarship'},
    {'title':'Fulbright Foreign Student Program','provider':'US Government','funding':'Full Scholarship','deadline':'Varies by country','eligibility':'African students for study in USA','link':'https://foreign.fulbrightonline.org','countries':'All African countries','level':'Masters & PhD in USA','category':'scholarship'},
    {'title':'Gates Cambridge Scholarship','provider':'Bill & Melinda Gates Foundation','funding':'Full Scholarship','deadline':'October annually','eligibility':'Outstanding students outside UK','link':'https://www.gatescambridge.org','countries':'All African countries','level':'Masters & PhD at Cambridge','category':'scholarship'},
]

JOBS = [
    {'title':'Youth Program Officer','company':'UN Women Africa','location':'Various African offices','type':'Full-time','deadline':'Rolling','link':'https://www.unwomen.org/careers','description':'Advance gender equality programs across Africa','category':'job'},
    {'title':'Climate Change Analyst','company':'UNDP Africa','location':'Addis Ababa, Ethiopia','type':'Full-time','deadline':'Rolling','link':'https://www.undp.org/careers','description':'Lead climate adaptation programs in Africa','category':'job'},
    {'title':'Education Program Manager','company':'USAID Africa','location':'Nairobi, Kenya','type':'Full-time','deadline':'Rolling','link':'https://www.usaid.gov/careers','description':'Manage education development programs','category':'job'},
    {'title':'Public Health Specialist','company':'WHO Africa','location':'Brazzaville, Congo','type':'Full-time','deadline':'Rolling','link':'https://www.who.int/careers','description':'Lead public health initiatives across Africa','category':'job'},
    {'title':'Financial Analyst','company':'African Export-Import Bank','location':'Cairo, Egypt','type':'Full-time','deadline':'Rolling','link':'https://www.afreximbank.com/careers','description':'Analyze trade finance opportunities in Africa','category':'job'},
    {'title':'Technology Innovation Officer','company':'GSMA Africa','location':'Nairobi, Kenya','type':'Full-time','deadline':'Rolling','link':'https://www.gsma.com/careers','description':'Drive mobile technology innovation in Africa','category':'job'},
    {'title':'Legal Officer','company':'African Development Bank','location':'Abidjan, Ivory Coast','type':'Full-time','deadline':'Rolling','link':'https://www.afdb.org/careers','description':'Provide legal support for development projects','category':'job'},
    {'title':'Supply Chain Manager','company':'MSF Africa','location':'Various African countries','type':'Full-time','deadline':'Rolling','link':'https://www.msf.org/careers','description':'Manage humanitarian supply chains across Africa','category':'job'},
    {'title':'Agricultural Development Officer','company':'FAO Africa','location':'Various African offices','type':'Full-time','deadline':'Rolling','link':'https://www.fao.org/careers','description':'Support food security and agricultural programs','category':'job'},
    {'title':'Media & Communications Officer','company':'ICRC Africa','location':'Nairobi, Kenya','type':'Full-time','deadline':'Rolling','link':'https://www.icrc.org/careers','description':'Manage communications for humanitarian operations','category':'job'},
    {'title':'Product Manager','company':'Flutterwave','location':'Lagos, Nigeria / Remote','type':'Full-time','deadline':'Rolling','link':'https://flutterwave.com/careers','description':'Build fintech products for African markets','category':'job'},
    {'title':'Data Scientist','company':'Safaricom','location':'Nairobi, Kenya','type':'Full-time','deadline':'Rolling','link':'https://www.safaricom.co.ke/careers','description':'Drive data insights for Africa leading telco','category':'job'},
    {'title':'UX Designer','company':'Interswitch Group','location':'Lagos, Nigeria','type':'Full-time','deadline':'Rolling','link':'https://www.interswitchgroup.com/careers','description':'Design digital payment experiences for Africa','category':'job'},
    {'title':'Operations Manager','company':'DHL Africa','location':'Johannesburg, South Africa','type':'Full-time','deadline':'Rolling','link':'https://careers.dhl.com','description':'Manage logistics operations across Africa','category':'job'},
    {'title':'Investment Analyst','company':'Helios Investment Partners','location':'Lagos / Nairobi','type':'Full-time','deadline':'Rolling','link':'https://www.heliosinvestment.com','description':'Analyze investment opportunities in Africa','category':'job'},
    {'title':'Community Development Officer','company':'Plan International Africa','location':'Various African offices','type':'Full-time','deadline':'Rolling','link':'https://www.plan-international.org/careers','description':'Implement community development programs','category':'job'},
    {'title':'Water & Sanitation Engineer','company':'UNICEF Africa','location':'Various African countries','type':'Full-time','deadline':'Rolling','link':'https://www.unicef.org/careers','description':'Improve water and sanitation across Africa','category':'job'},
    {'title':'Monitoring & Evaluation Officer','company':'World Food Programme Africa','location':'Various African offices','type':'Full-time','deadline':'Rolling','link':'https://www.wfp.org/careers','description':'Track impact of food security programs','category':'job'},
    {'title':'Cybersecurity Analyst','company':'MTN Group','location':'Johannesburg, South Africa','type':'Full-time','deadline':'Rolling','link':'https://www.mtn.com/careers','description':'Protect digital infrastructure across Africa','category':'job'},
    {'title':'Social Media Manager','company':'Equity Bank Africa','location':'Nairobi, Kenya','type':'Full-time','deadline':'Rolling','link':'https://equitygroupholdings.com/careers','description':'Manage digital communications for pan-African bank','category':'job'},

    {'title':'Program Officer - Youth Development','company':'UNICEF Africa','location':'Nairobi, Kenya','type':'Full-time','deadline':'Rolling','link':'https://www.unicef.org/careers','description':'Lead youth development programs across East Africa','category':'job'},
    {'title':'Communications Specialist','company':'African Union','location':'Addis Ababa, Ethiopia','type':'Full-time','deadline':'Rolling','link':'https://au.int/en/careers','description':'Manage communications for AU initiatives','category':'job'},
    {'title':'Data Analyst','company':'World Bank Africa','location':'Remote / Various African offices','type':'Full-time','deadline':'Rolling','link':'https://www.worldbank.org/en/about/careers','description':'Analyze development data across African projects','category':'job'},
    {'title':'Software Engineer','company':'Andela','location':'Remote - Africa','type':'Full-time','deadline':'Rolling','link':'https://andela.com/careers','description':'Join Africa largest tech talent network','category':'job'},
    {'title':'Project Manager - Health','company':'Partners in Health Africa','location':'Various African countries','type':'Full-time','deadline':'Rolling','link':'https://www.pih.org/careers','description':'Manage health projects in underserved communities','category':'job'},
    {'title':'Business Development Officer','company':'Tony Elumelu Foundation','location':'Lagos, Nigeria','type':'Full-time','deadline':'Rolling','link':'https://www.tonyelumelufoundation.org','description':'Support African entrepreneurs across the continent','category':'job'},
    {'title':'Research Associate','company':'African Economic Research Consortium','location':'Nairobi, Kenya','type':'Full-time','deadline':'Rolling','link':'https://www.aercafrica.org/careers','description':'Conduct economic research for African policy','category':'job'},
    {'title':'Digital Marketing Manager','company':'Jumia Africa','location':'Remote - Africa','type':'Full-time','deadline':'Rolling','link':'https://group.jumia.com/careers','description':'Drive digital marketing across African markets','category':'job'},
    {'title':'Community Health Worker','company':'Amref Health Africa','location':'Various African countries','type':'Full-time','deadline':'Rolling','link':'https://amref.org/careers','description':'Improve healthcare access in rural Africa','category':'job'},
    {'title':'Finance Officer','company':'Save the Children Africa','location':'Various African offices','type':'Full-time','deadline':'Rolling','link':'https://www.savethechildren.net/careers','description':'Manage finances for humanitarian programs','category':'job'},
]

GRANTS = [
    {'title':'African Entrepreneurs Fund','provider':'African Entrepreneurs Fund','amount':'Up to $25,000 USD','deadline':'Rolling','eligibility':'African entrepreneurs with viable business plans','link':'https://www.africanentrepreneursfund.org','countries':'All African countries','category':'grant'},
    {'title':'GSMA Innovation Fund Africa','provider':'GSMA','amount':'Up to $250,000 USD','deadline':'Rolling','eligibility':'African mobile technology startups','link':'https://www.gsma.com/innovation-fund','countries':'All African countries','category':'grant'},
    {'title':'African Development Bank Innovation Grant','provider':'African Development Bank','amount':'Up to $150,000 USD','deadline':'Rolling','eligibility':'African innovative enterprises','link':'https://www.afdb.org/grants','countries':'All African countries','category':'grant'},
    {'title':'Aga Khan Foundation Development Grant','provider':'Aga Khan Foundation','amount':'Varies','deadline':'Rolling','eligibility':'African civil society organizations','link':'https://www.akdn.org/agency/akf','countries':'Selected African countries','category':'grant'},
    {'title':'Comic Relief Africa Grant','provider':'Comic Relief UK','amount':'Up to £250,000','deadline':'Rolling','eligibility':'African NGOs working on poverty','link':'https://www.comicrelief.com/grants','countries':'Sub-Saharan Africa','category':'grant'},
    {'title':'MasterCard Foundation Rural & Agricultural Finance','provider':'Mastercard Foundation','amount':'Up to $500,000 USD','deadline':'Rolling','eligibility':'African organizations in agricultural finance','link':'https://mastercardfdn.org/grants','countries':'Sub-Saharan Africa','category':'grant'},
    {'title':'Global Innovation Fund Africa','provider':'Global Innovation Fund','amount':'$50,000 - $2M USD','deadline':'Rolling','eligibility':'African social innovations with evidence of impact','link':'https://www.globalinnovation.fund','countries':'All African countries','category':'grant'},
    {'title':'Rockefeller Foundation Africa Grants','provider':'Rockefeller Foundation','amount':'Varies','deadline':'Rolling','eligibility':'African organizations in food and health systems','link':'https://www.rockefellerfoundation.org','countries':'All African countries','category':'grant'},
    {'title':'Omidyar Network Africa Fund','provider':'Omidyar Network','amount':'Up to $1M USD','deadline':'Rolling','eligibility':'African social enterprises and nonprofits','link':'https://omidyar.com','countries':'All African countries','category':'grant'},
    {'title':'Vodafone Foundation Africa Grant','provider':'Vodafone Foundation','amount':'Up to £100,000','deadline':'Rolling','eligibility':'African organizations using tech for good','link':'https://www.vodafone.com/foundation','countries':'All African countries','category':'grant'},
    {'title':'UN Women Africa Innovation Grant','provider':'UN Women','amount':'Up to $50,000 USD','deadline':'Rolling','eligibility':'African organizations advancing gender equality','link':'https://www.unwomen.org/grants','countries':'All African countries','category':'grant'},
    {'title':'GIZ African SME Fund','provider':'GIZ Germany','amount':'Up to €100,000','deadline':'Rolling','eligibility':'African small and medium enterprises','link':'https://www.giz.de/africa-fund','countries':'Sub-Saharan Africa','category':'grant'},
    {'title':'African Media Initiative Grant','provider':'African Media Initiative','amount':'Up to $30,000 USD','deadline':'Rolling','eligibility':'African media organizations and journalists','link':'https://www.africanmediainitiative.org','countries':'All African countries','category':'grant'},
    {'title':'Clean Energy Solutions Center Africa','provider':'NREL / USAID','amount':'Up to $100,000 USD','deadline':'Rolling','eligibility':'African clean energy organizations','link':'https://cleanenergysolutions.org','countries':'All African countries','category':'grant'},
    {'title':'African Youth Trust Fund','provider':'African Union','amount':'Up to $50,000 USD','deadline':'March annually','eligibility':'African youth organizations 18-35','link':'https://au.int/youth-fund','countries':'All African countries','category':'grant'},
    {'title':'Skoll Foundation Africa Grant','provider':'Skoll Foundation','amount':'Up to $1.5M USD','deadline':'October annually','eligibility':'African social entrepreneurs with proven models','link':'https://skoll.org/grants','countries':'All African countries','category':'grant'},
    {'title':'MacArthur Foundation Africa Grants','provider':'MacArthur Foundation','amount':'Varies','deadline':'Rolling','eligibility':'African organizations in justice and sustainability','link':'https://www.macfound.org','countries':'All African countries','category':'grant'},
    {'title':'Barclays Africa Foundation Grant','provider':'Barclays Africa','amount':'Up to $50,000 USD','deadline':'Rolling','eligibility':'African youth entrepreneurs under 35','link':'https://home.barclays/africa-foundation','countries':'All African countries','category':'grant'},
    {'title':'Comic Relief Red Nose Day Africa','provider':'Comic Relief','amount':'Up to £150,000','deadline':'Rolling','eligibility':'African organizations working with vulnerable communities','link':'https://www.comicrelief.com','countries':'Sub-Saharan Africa','category':'grant'},
    {'title':'African Women Development Fund','provider':'AWDF','amount':'Up to $30,000 USD','deadline':'Rolling','eligibility':'African women-led organizations','link':'https://www.awdf.org','countries':'All African countries','category':'grant'},

    {'title':'Tony Elumelu Foundation Entrepreneurship Program','provider':'Tony Elumelu Foundation','amount':'$5,000 USD seed funding','deadline':'January annually','eligibility':'African entrepreneurs, early-stage businesses','link':'https://www.tonyelumelufoundation.org/teep','countries':'All 54 African countries','category':'grant'},
    {'title':'African Women Innovation Entrepreneurship Grant','provider':'AWIEF','amount':'Up to $10,000 USD','deadline':'Rolling','eligibility':'African women entrepreneurs','link':'https://awief.org','countries':'All African countries','category':'grant'},
    {'title':'Seedstars Africa Ventures Grant','provider':'Seedstars','amount':'Up to $500,000 USD investment','deadline':'Rolling','eligibility':'African tech startups','link':'https://www.seedstars.com','countries':'All African countries','category':'grant'},
    {'title':'Echoing Green Fellowship','provider':'Echoing Green','amount':'$80,000 USD over 2 years','deadline':'January annually','eligibility':'Social entrepreneurs with innovative ideas','link':'https://echoinggreen.org/fellowship','countries':'All African countries','category':'grant'},
    {'title':'Hivos Green Grants Africa','provider':'Hivos','amount':'Up to $50,000 USD','deadline':'Rolling','eligibility':'African organizations in renewable energy','link':'https://hivos.org/program/green-grants','countries':'Sub-Saharan Africa','category':'grant'},
    {'title':'African Capacity Building Foundation Grant','provider':'ACBF','amount':'Up to $200,000 USD','deadline':'Rolling','eligibility':'African institutions and organizations','link':'https://www.acbf-pact.org','countries':'All African countries','category':'grant'},
    {'title':'World Bank Youth Summit Grant','provider':'World Bank','amount':'Up to $10,000 USD','deadline':'March annually','eligibility':'African youth 18-30 with development projects','link':'https://www.worldbank.org/youthsummit','countries':'All African countries','category':'grant'},
    {'title':'Ford Foundation International Fellowships','provider':'Ford Foundation','amount':'Full fellowship support','deadline':'October annually','eligibility':'African social justice leaders','link':'https://www.fordfoundation.org','countries':'Selected African countries','category':'grant'},
    {'title':'African Union Youth Volunteer Corps Grant','provider':'African Union','amount':'Stipend + project funding','deadline':'Rolling','eligibility':'African youth 18-35','link':'https://au.int/en/AUYVC','countries':'All African countries','category':'grant'},
    {'title':'Wellcome Trust Africa Grants','provider':'Wellcome Trust','amount':'Up to 250,000 GBP','deadline':'Rolling','eligibility':'African researchers in health and science','link':'https://wellcome.org/grant-funding/schemes/african-programmes','countries':'All African countries','category':'grant'},
]


INTERNSHIPS = [
    {'title':'African Export-Import Bank Internship','company':'Afreximbank','location':'Cairo, Egypt','type':'Internship','deadline':'March annually','link':'https://www.afreximbank.com/careers','description':'Trade finance internship at pan-African bank','category':'internship','duration':'3-6 months','stipend':'Paid'},
    {'title':'UNDP Africa Policy Internship','company':'UNDP Africa','location':'Various African offices','type':'Internship','deadline':'Rolling','link':'https://www.undp.org/careers','description':'Policy research internship in development','category':'internship','duration':'6 months','stipend':'Stipend provided'},
    {'title':'African Union Peace & Security Internship','company':'African Union','location':'Addis Ababa, Ethiopia','type':'Internship','deadline':'April annually','link':'https://au.int/internship','description':'Peace and security policy internship','category':'internship','duration':'6 months','stipend':'Paid'},
    {'title':'Mastercard Foundation Internship','company':'Mastercard Foundation','location':'Toronto / Remote','type':'Internship','deadline':'Rolling','link':'https://mastercardfdn.org/careers','description':'Youth development program internship','category':'internship','duration':'4 months','stipend':'Paid'},
    {'title':'Tony Elumelu Foundation Internship','company':'Tony Elumelu Foundation','location':'Lagos, Nigeria','type':'Internship','deadline':'Rolling','link':'https://www.tonyelumelufoundation.org','description':'Entrepreneurship program internship','category':'internship','duration':'3 months','stipend':'Paid'},
    {'title':'Flutterwave Engineering Internship','company':'Flutterwave','location':'Lagos / Nairobi / Remote','type':'Internship','deadline':'Rolling','link':'https://flutterwave.com/careers','description':'Software engineering internship at African fintech','category':'internship','duration':'3-6 months','stipend':'Paid'},
    {'title':'WHO Africa Health Internship','company':'WHO Africa','location':'Brazzaville, Congo','type':'Internship','deadline':'Rolling','link':'https://www.who.int/careers','description':'Public health program internship','category':'internship','duration':'6 months','stipend':'Allowance provided'},
    {'title':'IFC Africa Investment Internship','company':'IFC World Bank Group','location':'Various African offices','type':'Internship','deadline':'Rolling','link':'https://www.ifc.org/careers','description':'Investment analysis internship in Africa','category':'internship','duration':'6 months','stipend':'Paid'},
    {'title':'Deloitte Africa Graduate Internship','company':'Deloitte Africa','location':'Johannesburg / Nairobi / Lagos','type':'Internship','deadline':'Rolling','link':'https://www2.deloitte.com/africa/careers','description':'Professional services internship at big 4','category':'internship','duration':'3-6 months','stipend':'Paid'},
    {'title':'Standard Bank Graduate Internship','company':'Standard Bank Africa','location':'Johannesburg, South Africa','type':'Internship','deadline':'Rolling','link':'https://www.standardbank.com/careers','description':'Banking and finance internship at pan-African bank','category':'internship','duration':'12 months','stipend':'Paid'},
    {'title':'Equity Bank Graduate Internship','company':'Equity Bank','location':'Nairobi, Kenya','type':'Internship','deadline':'Rolling','link':'https://equitygroupholdings.com/careers','description':'Banking internship at pan-African institution','category':'internship','duration':'6 months','stipend':'Paid'},
    {'title':'African Development Foundation Internship','company':'African Development Foundation','location':'Washington DC / Remote','type':'Internship','deadline':'Rolling','link':'https://www.adf.gov','description':'Development program internship focused on Africa','category':'internship','duration':'3-6 months','stipend':'Paid'},
    {'title':'Andela Fellowship Program','company':'Andela','location':'Remote - Africa','type':'Internship','deadline':'Rolling','link':'https://andela.com','description':'Software development fellowship for African developers','category':'internship','duration':'6 months','stipend':'Paid'},
    {'title':'Equity Bank Tech Internship','company':'Equity Bank','location':'Nairobi, Kenya','type':'Internship','deadline':'Rolling','link':'https://equitygroupholdings.com/careers','description':'Technology and digital banking internship','category':'internship','duration':'3 months','stipend':'Paid'},
    {'title':'GSMA Mobile for Development Internship','company':'GSMA','location':'Nairobi, Kenya','type':'Internship','deadline':'Rolling','link':'https://www.gsma.com/careers','description':'Mobile technology for development internship','category':'internship','duration':'6 months','stipend':'Paid'},
    {'title':'ReliefWeb Internship','company':'OCHA Africa','location':'Nairobi, Kenya','type':'Internship','deadline':'Rolling','link':'https://reliefweb.int/jobs','description':'Humanitarian information management internship','category':'internship','duration':'6 months','stipend':'Allowance provided'},
    {'title':'African Leadership University Internship','company':'African Leadership University','location':'Kigali / Mauritius','type':'Internship','deadline':'Rolling','link':'https://www.alueducation.com/careers','description':'Education innovation internship at pan-African university','category':'internship','duration':'3-6 months','stipend':'Paid'},
    {'title':'AMREF Health Africa Internship','company':'AMREF Health Africa','location':'Nairobi, Kenya','type':'Internship','deadline':'Rolling','link':'https://amref.org/careers','description':'Community health program internship','category':'internship','duration':'3-6 months','stipend':'Allowance'},
    {'title':'Mo Ibrahim Foundation Internship','company':'Mo Ibrahim Foundation','location':'London / Remote','type':'Internship','deadline':'Rolling','link':'https://mo.ibrahim.foundation','description':'African governance research internship','category':'internship','duration':'3-6 months','stipend':'Paid'},
    {'title':'Airtel Africa Graduate Internship','company':'Airtel Africa','location':'Various African countries','type':'Internship','deadline':'Rolling','link':'https://airtel.africa/careers','description':'Telecoms and digital services internship','category':'internship','duration':'6 months','stipend':'Paid'},

    {'title':'UN Youth Volunteer Programme 2025','company':'United Nations','location':'Various African offices','type':'Internship','deadline':'Rolling','link':'https://www.unv.org','description':'6-12 month volunteer internship with UN agencies across Africa','category':'internship','duration':'6-12 months','stipend':'Monthly allowance provided'},
    {'title':'African Development Bank Internship','company':'African Development Bank','location':'Abidjan, Ivory Coast','type':'Internship','deadline':'March & September annually','link':'https://www.afdb.org/en/careers/internships','description':'6-month internship in finance, economics, or development','category':'internship','duration':'6 months','stipend':'Paid'},
    {'title':'World Health Organization Africa Internship','company':'WHO Africa','location':'Brazzaville, Congo','type':'Internship','deadline':'Rolling','link':'https://www.who.int/careers/internships','description':'Health policy and program internship in Africa','category':'internship','duration':'6 months','stipend':'Unpaid with allowance'},
    {'title':'Google Africa Developer Internship','company':'Google','location':'Remote / Nairobi / Lagos','type':'Internship','deadline':'Rolling','link':'https://careers.google.com','description':'Software engineering internship for African developers','category':'internship','duration':'3-6 months','stipend':'Paid'},
    {'title':'Microsoft Africa Research Institute Internship','company':'Microsoft','location':'Nairobi, Kenya','type':'Internship','deadline':'Rolling','link':'https://www.microsoft.com/en-us/research/lab/microsoft-research-africa','description':'AI and technology research internship','category':'internship','duration':'3-6 months','stipend':'Paid'},
    {'title':'UNICEF Africa Internship Programme','company':'UNICEF','location':'Various African countries','type':'Internship','deadline':'Rolling','link':'https://www.unicef.org/careers/internships','description':'Work on child rights and development programs','category':'internship','duration':'6 months','stipend':'Stipend provided'},
    {'title':'African Union Commission Internship','company':'African Union','location':'Addis Ababa, Ethiopia','type':'Internship','deadline':'January & July annually','link':'https://au.int/en/internship','description':'Policy and governance internship at AU headquarters','category':'internship','duration':'6 months','stipend':'Paid'},
    {'title':'GIZ Africa Internship','company':'GIZ Germany','location':'Various African countries','type':'Internship','deadline':'Rolling','link':'https://www.giz.de/en/html/jobs.html','description':'Development cooperation internship across Africa','category':'internship','duration':'3-6 months','stipend':'Paid'},
    {'title':'Safaricom Internship Programme','company':'Safaricom','location':'Nairobi, Kenya','type':'Internship','deadline':'Rolling','link':'https://www.safaricom.co.ke/careers','description':'Tech and business internship at Africa leading telco','category':'internship','duration':'3 months','stipend':'Paid'},
    {'title':'MTN Group Internship','company':'MTN Group','location':'Johannesburg / Various African countries','type':'Internship','deadline':'Rolling','link':'https://www.mtn.com/careers','description':'Telecommunications and digital services internship','category':'internship','duration':'3-6 months','stipend':'Paid'},
]

FELLOWSHIPS = [
    {'title':'Young African Leaders Initiative YALI','company':'US Government','location':'USA + Africa','type':'Fellowship','deadline':'October annually','link':'https://yali.state.gov','description':'Leadership training for young African leaders','category':'fellowship','duration':'6 weeks','stipend':'Fully funded'},
    {'title':'African Leadership Initiative','company':'Aspen Institute','location':'Various African cities','type':'Fellowship','deadline':'Rolling','link':'https://www.aspenafricaleadership.org','description':'Senior leadership fellowship for African executives','category':'fellowship','duration':'1 year','stipend':'Partially funded'},
    {'title':'Desmond Tutu Fellowship','company':'Desmond Tutu Peace Foundation','location':'South Africa','type':'Fellowship','deadline':'March annually','link':'https://www.tutu.org.za','description':'Peace and reconciliation fellowship','category':'fellowship','duration':'1 year','stipend':'Stipend provided'},
    {'title':'Africa Climate Fellowship','company':'African Climate Foundation','location':'Cape Town, South Africa','type':'Fellowship','deadline':'February annually','link':'https://africanclimatefoundation.org','description':'Climate policy fellowship for African leaders','category':'fellowship','duration':'1 year','stipend':'Fully funded'},
    {'title':'Skoll Foundation Social Entrepreneurship Fellowship','company':'Skoll Foundation','location':'Oxford, UK','type':'Fellowship','deadline':'October annually','link':'https://skoll.org/fellowship','description':'Social entrepreneurship fellowship at Said Business School','category':'fellowship','duration':'1 year','stipend':'Fully funded'},
    {'title':'Dalberg African Fellowship','company':'Dalberg Group','location':'Various African offices','type':'Fellowship','deadline':'Rolling','link':'https://dalberg.com/careers','description':'Development consulting fellowship in Africa','category':'fellowship','duration':'1-2 years','stipend':'Paid'},
    {'title':'African Women Leadership Fund Fellowship','company':'AWLF','location':'Various African countries','type':'Fellowship','deadline':'March annually','link':'https://www.awlf.org','description':'Leadership fellowship for African women change-makers','category':'fellowship','duration':'1 year','stipend':'Fully funded'},
    {'title':'Bill & Melinda Gates Foundation Africa Fellowship','company':'Gates Foundation','location':'Seattle / Africa','type':'Fellowship','deadline':'January annually','link':'https://www.gatesfoundation.org/careers','description':'Global health and development fellowship','category':'fellowship','duration':'2 years','stipend':'Fully funded'},
    {'title':'World Economic Forum Young Global Leaders','company':'World Economic Forum','location':'Davos + Virtual','type':'Fellowship','deadline':'September annually','link':'https://www.weforum.org/ygl','description':'Fellowship for outstanding African leaders under 40','category':'fellowship','duration':'5 years','stipend':'Partially funded'},
    {'title':'Carnegie African Diaspora Fellowship','company':'Carnegie Corporation','location':'African universities','type':'Fellowship','deadline':'December annually','link':'https://www.iie.org/cadfp','description':'Fellowship for African diaspora academics','category':'fellowship','duration':'1-3 months','stipend':'Fully funded'},
    {'title':'Amani Institute Social Innovation Fellowship','company':'Amani Institute','location':'Nairobi / Addis Ababa','type':'Fellowship','deadline':'Rolling','link':'https://www.amaniinstitute.org','description':'Social innovation and leadership fellowship','category':'fellowship','duration':'5 months','stipend':'Partially funded'},
    {'title':'Meridian International Center Fellowship','company':'Meridian International','location':'Washington DC','type':'Fellowship','deadline':'Rolling','link':'https://www.meridian.org','description':'International leadership exchange fellowship','category':'fellowship','duration':'3-4 weeks','stipend':'Fully funded'},
    {'title':'African Storybook Initiative Fellowship','company':'African Storybook','location':'Johannesburg, South Africa','type':'Fellowship','deadline':'Rolling','link':'https://www.africanstorybook.org','description':'Education and literacy fellowship in Africa','category':'fellowship','duration':'6 months','stipend':'Stipend provided'},
    {'title':'Open Society Foundations Africa Fellowship','company':'Open Society Foundations','location':'Various African countries','type':'Fellowship','deadline':'Rolling','link':'https://www.opensocietyfoundations.org','description':'Civil society and governance fellowship','category':'fellowship','duration':'1 year','stipend':'Fully funded'},
    {'title':'Vital Voices Africa Fellowship','company':'Vital Voices','location':'Washington DC + Africa','type':'Fellowship','deadline':'February annually','link':'https://www.vitalvoices.org','description':'Leadership fellowship for African women leaders','category':'fellowship','duration':'1 year','stipend':'Fully funded'},
    {'title':'African Climate Reality Project Fellowship','company':'Climate Reality Project','location':'Various African cities','type':'Fellowship','deadline':'Rolling','link':'https://www.climaterealityproject.org','description':'Climate change leadership fellowship for Africans','category':'fellowship','duration':'3 days training + ongoing','stipend':'Funded'},
    {'title':'Population Council Africa Fellowship','company':'Population Council','location':'Nairobi / Accra','type':'Fellowship','deadline':'Rolling','link':'https://www.popcouncil.org/careers','description':'Research fellowship in population health in Africa','category':'fellowship','duration':'1-2 years','stipend':'Paid'},
    {'title':'Right Livelihood Award Foundation Fellowship','company':'Right Livelihood Foundation','location':'Stockholm + Africa','type':'Fellowship','deadline':'March annually','link':'https://www.rightlivelihood.org','description':'Fellowship for African social change makers','category':'fellowship','duration':'1 year','stipend':'Fully funded'},
    {'title':'Pan-African University Fellowship','company':'African Union','location':'Various African universities','type':'Fellowship','deadline':'March annually','link':'https://pau.africa','description':'Postgraduate fellowship at Pan-African University','category':'fellowship','duration':'2 years','stipend':'Full stipend'},
    {'title':'African Science Academy Fellowship','company':'African Academy of Sciences','location':'Nairobi, Kenya','type':'Fellowship','deadline':'October annually','link':'https://www.aasciences.africa','description':'Science research fellowship for African scientists','category':'fellowship','duration':'1-3 years','stipend':'Paid'},

    {'title':'Obama Foundation Leaders Africa Program','company':'Obama Foundation','location':'Various African cities','type':'Fellowship','deadline':'February annually','link':'https://www.obama.org/programs/leaders/africa','description':'Leadership fellowship for African change-makers under 40','category':'fellowship','duration':'1 year','stipend':'Fully funded'},
    {'title':'Mandela Washington Fellowship','company':'US Department of State','location':'USA + home country','type':'Fellowship','deadline':'November annually','link':'https://yali.state.gov/mwf','description':'6-week leadership institute in USA for African youth','category':'fellowship','duration':'6 weeks','stipend':'Fully funded'},
    {'title':'Acumen East Africa Fellowship','company':'Acumen','location':'East Africa','type':'Fellowship','deadline':'February annually','link':'https://acumen.org/fellowships','description':'Social enterprise leadership fellowship','category':'fellowship','duration':'1 year','stipend':'Stipend provided'},
    {'title':'African Leadership Academy Fellowship','company':'African Leadership Academy','location':'Johannesburg, South Africa','type':'Fellowship','deadline':'October annually','link':'https://www.africanleadershipacademy.org','description':'Leadership development for young African leaders','category':'fellowship','duration':'2 years','stipend':'Scholarship + stipend'},
    {'title':'Aspen New Voices Fellowship','company':'Aspen Institute','location':'Various','type':'Fellowship','deadline':'Rolling','link':'https://www.aspeninstitute.org','description':'Fellowship for African development thinkers and practitioners','category':'fellowship','duration':'1 year','stipend':'Fully funded'},
    {'title':'Atlantic Fellows for Social and Economic Equity','company':'Atlantic Institute','location':'London + Africa','type':'Fellowship','deadline':'January annually','link':'https://www.atlanticfellows.org','description':'Fellowship addressing inequality in Africa','category':'fellowship','duration':'1 year','stipend':'Fully funded'},
    {'title':'Schwarzman Scholars Program','company':'Schwarzman College','location':'Beijing, China','type':'Fellowship','deadline':'September annually','link':'https://www.schwarzmanscholars.org','description':'Masters degree fellowship at Tsinghua University','category':'fellowship','duration':'1 year','stipend':'Fully funded'},
    {'title':'African Development Bank Young Professionals','company':'African Development Bank','location':'Abidjan, Ivory Coast','type':'Fellowship','deadline':'January annually','link':'https://www.afdb.org/en/careers/young-professionals-program','description':'3-year professional fellowship at AfDB','category':'fellowship','duration':'3 years','stipend':'Full salary'},
    {'title':'TED Fellows Program','company':'TED','location':'Remote + TED Conference','type':'Fellowship','deadline':'May annually','link':'https://fellowships.ted.com','description':'Fellowship for innovative African thinkers and doers','category':'fellowship','duration':'2 years','stipend':'Travel + support'},
    {'title':'Hubert H. Humphrey Fellowship','company':'US Department of State','location':'USA','type':'Fellowship','deadline':'October annually','link':'https://www.humphreyfellowship.org','description':'10-month professional development fellowship in USA','category':'fellowship','duration':'10 months','stipend':'Fully funded'},
]

def post_opportunities():
    now = datetime.now(timezone.utc)
    week = now.strftime("%Y-W%U")
    posted = 0
    print(f"\n🌍 YAN Weekly Opportunities Worker")
    print(f"📅 Week: {week}\n")
    print("📚 Posting scholarships...")
    for s in SCHOLARSHIPS:
        doc_id = f"weekly-{week}-{s['title'][:30].replace(' ','-').lower()}"
        db.collection("scholarships").document(doc_id).set({**s,"postedAt":now,"postedBy":"YAN Opportunities Bot","weekRef":week,"verified":True,"status":"active"})
        posted += 1
        print(f"  ✅ {s['title'][:50]}")
    print("\n💼 Posting jobs...")
    for j in JOBS:
        doc_id = f"weekly-{week}-{j['title'][:30].replace(' ','-').lower()}"
        db.collection("careerJobs").document(doc_id).set({**j,"postedAt":now,"postedById":"yan-bot","weekRef":week,"verified":True,"status":"active"})
        posted += 1
        print(f"  ✅ {j['title'][:50]}")
    print("\n🎓 Posting internships...")
    for i in INTERNSHIPS:
        doc_id = f"weekly-{week}-intern-{i['title'][:25].replace(' ','-').lower()}"
        db.collection("careerJobs").document(doc_id).set({**i,"postedAt":now,"postedById":"yan-bot","weekRef":week,"verified":True,"status":"active"})
        posted += 1
        print(f"  ✅ {i['title'][:50]}")
    print("\n🌟 Posting fellowships...")
    for f in FELLOWSHIPS:
        doc_id = f"weekly-{week}-fellow-{f['title'][:25].replace(' ','-').lower()}"
        db.collection("careerJobs").document(doc_id).set({**f,"postedAt":now,"postedById":"yan-bot","weekRef":week,"verified":True,"status":"active"})
        posted += 1
        print(f"  ✅ {f['title'][:50]}")
    print("\n💰 Posting grants...")
    for g in GRANTS:
        doc_id = f"weekly-{week}-grant-{g['title'][:30].replace(' ','-').lower()}"
        db.collection("scholarships").document(doc_id).set({**g,"postedAt":now,"postedBy":"YAN Opportunities Bot","weekRef":week,"verified":True,"status":"active","funding":g["amount"]})
        posted += 1
        print(f"  ✅ {g['title'][:50]}")
    try:
        db.collection("notifications").add({"title":"🌍 New Opportunities This Week!","message":"10 scholarships, 10 jobs, 10 internships, 10 fellowships and 10 grants posted this week. Check YAN now!","type":"opportunity","postedBy":"YAN Opportunities Bot","createdAt":now,"readBy":[]})
        print(f"\n🔔 Notification sent to all members!")
    except Exception as e:
        print(f"⚠️  Notification failed: {e}")
    print(f"\n🎉 Done! {posted} opportunities posted for week {week}")

post_opportunities()
# This line intentionally left blank
